language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

services:
  - postgresql

addons:
  apt:
    packages:
      - rabbitmq-server
env:
  # - DJANGO="x.y.z"
  global:
  - DJANGO_SETTINGS_MODULE="vavilov3_web.settings"
  - PYTHONPATH="/home/travis/build/pziarsolo/vavilov3:/home/travis/build/pziarsolo/vavilov3_web"
  - PIP_USE_MIRRORS=true

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls radon requests

before_script:
  - echo "DJANGO_SECRET_KEY = 'i)^!7-o8zdtz1(kba*k(15pe6qwqsx*nl$+9)biux2iXXXxxxe*'" > vavilov3_web/vavilov3_web/secret_keys.py
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - python vavilov3_web/manage.py makemigrations
  - python vavilov3_web/manage.py migrate
  - python vavilov3_web/manage.py initialize_db -u vavilov3/tests/data/csvs/users.csv;
  - python vavilov3_web/manage.py runserver &
  - cd vavilov3_web
  - celery worker -A vavilov3_web -l info &
  - cd ..


# command to run tests
script:
  - coverage run --source=. vavilov3_web/manage.py test vavilov3 --noinput --settings=vavilov3_web.settings
  - vavilov3/tests/add_test_data_bulk.py
after_success:
  - coveralls
