language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

services: postgresql
env:
  global:
# - DJANGO="x.y.z"
  - DJANGO_SETTINGS_MODULE="vavilov3_web.settings"
  - PYTHONPATH="/home/travis/build/pziarsolo/vavilov3:/home/travis/build/pziarsolo/vavilov3_web"
  - PIP_USE_MIRRORS=true

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls radon

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - cd vavilov3_web

# command to run tests
script:
  - python manage.py test vavilov3
