# Generated by Django 2.2.2 on 2019-07-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vavilov3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationvariable',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov3.Scale'),
        ),
        migrations.AlterField(
            model_name='observationvariable',
            name='trait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov3.Trait'),
        ),
    ]
