#
# Copyright (C) 2019 P.Ziarsolo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#

# Generated by Django 2.2.2 on 2019-07-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vavilov3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationvariable',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov3.Scale'),
        ),
        migrations.AlterField(
            model_name='observationvariable',
            name='trait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov3.Trait'),
        ),
    ]
