# Generated by Django 2.2.10 on 2020-03-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vavilov3', '0002_auto_20190726_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accession',
            old_name='is_save_duplicate',
            new_name='in_nuclear_collection',
        ),
    ]
