# Generated by Django 2.2.11 on 2020-04-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vavilov3', '0003_auto_20200306_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='level',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
