# Generated by Django 2.2.11 on 2020-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vavilov3', '0005_seedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='end_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='start_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
