# Generated by Django 2.2.11 on 2020-12-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vavilov3', '0006_auto_20200505_1021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observationvariable',
            unique_together=set(),
        ),
    ]
