from django.conf import settings

ADMIN_GROUP = getattr(settings, 'VAVILOV3_ADMIN_GROUP', 'admin')

ALLOWED_TAXONOMIC_RANKS = ['family', 'genus', 'species', 'subspecies',
                           'variety', 'convarietas', 'group', 'forma']
USERS_CAN_CREATE_ACCESSIONSETS = getattr(
    settings, 'VAVILOV3_USERS_CAN_CREATE_ACCESSIONSETS', False)

DEF_ACCESSION_CSV_FIELDS = [
    'PUID', 'INSTCODE', 'ACCENUMB', 'CONSTATUS', 'IS_AVAILABLE', 'COLLNUMB',
    'COLLCODE', 'GENUS', 'SPECIES', 'SPAUTHOR', 'SUBTAXA', 'SUBTAUTHOR',
    'CROPNAME', 'ACCENAME', 'ACQDATE', 'ORIGCTY', 'COLLSITE',
    'LATITUDE', 'LONGITUDE', 'COORDUNCERT', 'COORDDATUM',
    'GEOREFMETH', 'ELEVATION', 'COLLDATE', 'BREDCODE',
    'SAMPSTAT', 'ANCEST', 'COLLSRC', 'DONORCODE', 'DONORNUMB',
    'OTHERNUMB', 'DUPLSITE', 'STORAGE', 'MLSSTAT', 'REMARKS']
ACCESSION_CSV_FIELDS = getattr(settings, 'VAVILOV3_ACCESSION_CSV_FIELDS',
                               DEF_ACCESSION_CSV_FIELDS)

DEF_ACCESSIONSET_CSV_FIELDS = ['INSTCODE', 'ACCESETNUMB', 'ACCESSIONS']
ACCESSIONSET_CSV_FIELDS = getattr(settings, 'VAVILOV3_ACCESSIONSET_CSV_FIELDS',
                                  DEF_ACCESSIONSET_CSV_FIELDS)
DEF_INSTITUTE_CSV_FIELDS = ['INSTCODE', 'FULL_NAME', 'TYPE']
INSTITUTE_CSV_FIELDS = getattr(settings, 'VAVILOV3_INSTITUTE_CSV_FIELDS',
                               DEF_INSTITUTE_CSV_FIELDS)
